version: '3'

services:
  web:
    image: apache
    build: .
    ports:
      - "8080:80"
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web
    command: npx cypress run --browser chrome
